FROM node:20-alpine

RUN apk add --no-cache libssl1.1

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY backend/package.json backend/package-lock.json* ./
COPY backend/prisma ./prisma

RUN npm install
RUN npx prisma generate

# Copy the rest of the backend code
COPY backend/ .

# Expose the backend port
EXPOSE 5000

# Start the backend
CMD ["npm", "run", "dev"]