services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      BACKEND_URL: ${BACKEND_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge